<header>
    <h1>Acompanhe suas consultas</h1>
</header>
<main>

    <?php if(isset($_GET['error'])){ ?>
        <p>Horário Indisponível</p>
    <?php } ?>

    <section class="create-card">
        <form action="/appointment?action=create" method="POST">
            <label>Nome (Paciente)</label>
            <input type="text" name="name">
            <label>Email (Paciente)</label>
            <input type="email" name="email" id="">
            <label>Data e hora da consulta</label>
            <input type="datetime-local" name="datetime">
            <button>Marcar</button>
        </form>

        <div class="div-link">
            <a href="/appointment?action=show">Ver consultas agendadas</a>
        </div>
    </section>
</main>

